Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true     ## This is the extra plugins 
  config.hostmanager.manage_host = true ## This is the extra plugins 
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.10.11"
    db01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end

  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.10.12"
    mc01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
  end
  
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
  rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.10.13"
    rmq01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
  end
  
### tomcat vm or webapp###
   config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.10.14"
    app01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
   end
   
  
### Nginx VM or Load Balancer ###
  config.vm.define "lb01" do |lb01|
    lb01.vm.box = "ubuntu/jammy64"
    lb01.vm.hostname = "lb01"
  lb01.vm.network "private_network", ip: "192.168.10.15"
  lb01.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
   end
end
  
end